// @ts-expect-error - regenerated by `npx expo prebuild --clean`
import { requireOptionalNativeModule } from "expo-modules-core"
import type { ExpoExternalPlayerModuleType } from "./ExpoExternalPlayer.types"

const ExpoExternalPlayerModule = requireOptionalNativeModule<ExpoExternalPlayerModuleType>("ExpoExternalPlayer")

export default ExpoExternalPlayerModule
