// @ts-expect-error - regenerated by `npx expo prebuild --clean`
import { requireOptionalNativeModule } from "expo-modules-core"
import type { ExpoOfflineLoggerModuleType } from "./ExpoOfflineLogger.types"

const ExpoOfflineLoggerModule = requireOptionalNativeModule<ExpoOfflineLoggerModuleType>("ExpoOfflineLogger")

export default ExpoOfflineLoggerModule